version: "3.9"

services:
  db:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  server:
    depends_on:
      - db
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - AWS_API_VERSION=$AWS_API_VERSION
      - AWS_ACCESS_KEY=$AWS_ACCESS_KEY
      - AWS_SECRET_KEY=$AWS_SECRET_KEY
      - AWS_BUCKET=$AWS_BUCKET
      - RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY
      - DB_HOST=db
      - DB_PORT=$DB_DOCKER_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - NODE_ENV=$NODE_ENV
    networks:
      - backend
      - frontend
  client:
    depends_on:
      - server
    build:
      context: ./client
      args:
        - REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL
        - REACT_APP_RECAPTCHA_SITEKEY=$REACT_APP_RECAPTCHA_SITEKEY
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - frontend

volumes:
  db:

networks:
  backend:
  frontend:
